DROP TABLE IF EXISTS REGION CASCADE;\g
CREATE TABLE REGION (
 R_REGIONKEY INT PRIMARY KEY,
 R_NAME CHAR(25),
 R_COMMENT VARCHAR(152)
);\g

DROP TABLE IF EXISTS NATION CASCADE;\g
CREATE TABLE NATION (
 N_NATIONKEY INT PRIMARY KEY,
 N_NAME CHAR(25),
 N_REGIONKEY BIGINT NOT NULL, -- references R_REGIONKEY
 N_COMMENT VARCHAR(152)
);\g

DROP TABLE IF EXISTS CUSTOMER CASCADE;\g
CREATE TABLE CUSTOMER (
 C_CUSTKEY INT PRIMARY KEY,
 C_NAME VARCHAR(25),
 C_ADDRESS VARCHAR(40),
 C_NATIONKEY BIGINT NOT NULL, -- references N_NATIONKEY
 C_PHONE CHAR(15),
 C_ACCTBAL FLOAT,
 C_MKTSEGMENT CHAR(10),
 C_COMMENT VARCHAR(117)
);\g

DROP TABLE IF EXISTS PART CASCADE;\g
CREATE TABLE PART (
 P_PARTKEY INT PRIMARY KEY,
 P_NAME VARCHAR(55),
 P_MFGR CHAR(25),
 P_BRAND CHAR(10),
 P_TYPE VARCHAR(25),
 P_SIZE INTEGER,
 P_CONTAINER CHAR(10),
 P_RETAILPRICE FLOAT,
 P_COMMENT VARCHAR(23)
);\g

DROP TABLE IF EXISTS SUPPLIER CASCADE;\g
CREATE TABLE SUPPLIER (
 S_SUPPKEY INT PRIMARY KEY,
 S_NAME CHAR(25),
 S_ADDRESS VARCHAR(40),
 S_NATIONKEY BIGINT NOT NULL, -- references N_NATIONKEY
 S_PHONE CHAR(15),
 S_ACCTBAL FLOAT,
 S_COMMENT VARCHAR(101)
);\g

DROP TABLE IF EXISTS PARTSUPP CASCADE;\g
CREATE TABLE PARTSUPP (
 PS_PARTKEY BIGINT NOT NULL, -- references P_PARTKEY
 PS_SUPPKEY BIGINT NOT NULL, -- references S_SUPPKEY
 PS_AVAILQTY INTEGER,
 PS_SUPPLYCOST FLOAT,
 PS_COMMENT VARCHAR(199),
 PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);\g

DROP TABLE IF EXISTS ORDERS CASCADE;\g
CREATE TABLE ORDERS (
 O_ORDERKEY INT PRIMARY KEY,
 O_CUSTKEY BIGINT NOT NULL, -- references C_CUSTKEY
 O_ORDERSTATUS CHAR(1),
 O_TOTALPRICE FLOAT,
 O_ORDERDATE DATE,
 O_ORDERPRIORITY CHAR(15),
 O_CLERK CHAR(15),
 O_SHIPPRIORITY INTEGER,
 O_COMMENT VARCHAR(79)
);\g

DROP TABLE IF EXISTS LINEITEM CASCADE;\g
CREATE TABLE LINEITEM (
 L_ORDERKEY BIGINT NOT NULL, -- references O_ORDERKEY
 L_PARTKEY BIGINT NOT NULL, -- references P_PARTKEY (compound fk to PARTSUPP)
 L_SUPPKEY BIGINT NOT NULL, -- references S_SUPPKEY (compound fk to PARTSUPP)
 L_LINENUMBER INTEGER NOT NULL,
 L_QUANTITY FLOAT,
 L_EXTENDEDPRICE FLOAT,
 L_DISCOUNT FLOAT,
 L_TAX FLOAT,
 L_RETURNFLAG CHAR(1),
 L_LINESTATUS CHAR(1),
 L_SHIPDATE DATE,
 L_COMMITDATE DATE,
 L_RECEIPTDATE DATE,
 L_SHIPINSTRUCT CHAR(25),
 L_SHIPMODE CHAR(10),
 L_COMMENT VARCHAR(44),
 PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);\g
